apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/build-id: 2273ce5c-aa5d-4306-b3f9-9b67a6fc711a
    run.googleapis.com/build-image-uri: europe-central2-docker.pkg.dev/dzialkizamniej/cloud-run-source-deploy/universe-mapmaker
    run.googleapis.com/build-name: projects/1004166685896/locations/global/builds/2273ce5c-aa5d-4306-b3f9-9b67a6fc711a
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://universe-mapmaker-1004166685896.europe-central2.run.app","https://universe-mapmaker-bhlj652crq-lm.a.run.app"]'
  labels:
    cloud.googleapis.com/location: europe-central2
  name: universe-mapmaker
  namespace: '1004166685896'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '5'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 540.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: evtsaftkrv
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: GOOGLE_SHEETS_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: google-sheets-private-key
        - name: GOOGLE_SHEETS_SERVICE_ACCOUNT_EMAIL
          valueFrom:
            secretKeyRef:
              key: latest
              name: google-sheets-service-account
        - name: GOOGLE_SHEETS_SPREADSHEET_ID
          valueFrom:
            secretKeyRef:
              key: latest
              name: google-sheets-spreadsheet-id
        - name: GEOSERVER_URL
          valueFrom:
            secretKeyRef:
              key: latest
              name: geoserver-url
        - name: GEOSERVER_USERNAME
          valueFrom:
            secretKeyRef:
              key: latest
              name: geoserver-username
        - name: GEOSERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: geoserver-password
        - name: NODE_ENV
          value: production
        - name: NEXT_TELEMETRY_DISABLED
          value: '1'
        - name: NEXT_PUBLIC_MAPBOX_TOKEN
          value: pk.eyJ1IjoibWFwbWFrZXItb25saW5lIiwiYSI6ImNtZzN3bm8wYTBwaXIybHM5dDlpc3YwOTQifQ.8Hrv97gishqnvI_h7PiqlQ
        - name: NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
          value: pk.eyJ1IjoibWFwbWFrZXItb25saW5lIiwiYSI6ImNtZzN3bm8wYTBwaXIybHM5dDlpc3YwOTQifQ.8Hrv97gishqnvI_h7PiqlQ
        image: europe-central2-docker.pkg.dev/dzialkizamniej/universe-mapmaker/app:fd9e24fea0973b587b99a7a30455866f429682ce
        ports:
        - containerPort: 3000
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 3000
          timeoutSeconds: 240
      serviceAccountName: 1004166685896-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
