# Cloud Run service configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: universe-mapmaker
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "2"
        run.googleapis.com/max-scale: "10"
        run.googleapis.com/min-scale: "0"
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/universe-mapmaker:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        - name: PORT
          value: "8080"
        - name: HOSTNAME
          value: "0.0.0.0"
        # Secrets from Google Secret Manager
        - name: GOOGLE_SHEETS_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: google-sheets-private-key
              key: latest
        - name: GOOGLE_SHEETS_SERVICE_ACCOUNT_EMAIL
          valueFrom:
            secretKeyRef:
              name: google-sheets-service-account
              key: latest
        - name: GOOGLE_SHEETS_SPREADSHEET_ID
          valueFrom:
            secretKeyRef:
              name: google-sheets-spreadsheet-id
              key: latest
        - name: GEOSERVER_URL
          valueFrom:
            secretKeyRef:
              name: geoserver-url
              key: latest
        - name: GEOSERVER_USERNAME
          valueFrom:
            secretKeyRef:
              name: geoserver-username
              key: latest
        - name: GEOSERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: geoserver-password
              key: latest
        - name: MAPBOX_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: mapbox-access-token
              key: latest
        resources:
          limits:
            cpu: "2000m"
            memory: "2Gi"
          requests:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true
